---
title: "R Notebook"
output: html_notebook
---

```{r}
df <- read.csv(file='normalized_df.csv')
head(df)
```



```{r}
#install.packages("caret", dependencies=TRUE)
library(gbm)          # basic implementation
library(caret)

getModelInfo()$gbm$type

outcomeName <- 'outcome'
predictorsNames <- names(df)[names(df) != outcomeName]


df$outcome2 <- ifelse(df$outcome==1,'yes','no')
df$outcome2 <- as.factor(df$outcome2)
outcomeName <- 'outcome2'

```


```{r}
set.seed(1234)
splitIndex <- createDataPartition(df[,outcomeName], p = .85, list = FALSE, times = 1)
trainDF <- df[ splitIndex,]
testDF  <- df[-splitIndex,]

```

```{r}

objControl <- trainControl(method='cv', 
                           number=3, 
                           returnResamp='none', 
                           summaryFunction = twoClassSummary, 
                           classProbs = TRUE)

objModel <- train(trainDF[,predictorsNames], trainDF[,outcomeName], 
                  method='gbm', 
                  trControl=objControl,  
                  metric = "ROC",
                  preProc = c("center", "scale"))

summary(objModel)

```


```{r}
print(objModel)
```


```{r}
predictions <- predict(object=objModel, testDF[,predictorsNames], type='raw')
head(predictions)
```

```{r}
print(postResample(pred=predictions, obs=as.factor(testDF[,outcomeName])))
```

```{r}
library(pROC)
predictions <- predict(object=objModel, testDF[,predictorsNames], type='prob')
head(predictions)
```

```{r}
auc <- roc(ifelse(testDF[,outcomeName]=="yes",1,0), predictions[[2]])
print(auc$auc)
```


```{r}
getModelInfo()$glmnet$type
## [1] "Regression"     "Classification"
outcomeName <- 'outcome'

set.seed(1234)
splitIndex <- createDataPartition(df[,outcomeName], p = .85, list = FALSE, times = 1)
trainDF <- df[ splitIndex,]
testDF  <- df[-splitIndex,]


objControl <- trainControl(method='cv', number=3, returnResamp='none')
objModel <- train(trainDF[,predictorsNames], trainDF[,outcomeName], method='glmnet',  metric = "RMSE", trControl=objControl)
predictions <- predict(object=objModel, testDF[,predictorsNames])
auc <- roc(testDF[,outcomeName], predictions)
print(auc$auc)
```

```{r}
plot(varImp(objModel,scale=F))
```